name: Backend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -i private_key -o StrictHostKeyChecking=no -r ./* ${USER}@${HOST}:/home/ubuntu/gouris-backend/
          ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
            cd /home/ubuntu/gouris-backend
            npm ci --only=production
            pm2 restart gouris-server || pm2 start npm --name "gouris-server" -- run start
            pm2 save
            sudo systemctl reload nginx
          '
